# (PART\*) Background {-}


```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Introduction

This is a companion training guide for BioDIGS, a GDSCN project that brings a research experience into the classroom. Visit the BioDIGS (BioDiversity and Informatics for Genomics Scholars) website [here](https://biodigs.org/) for more information about this collaborative, distributed research project!

The GDSCN (Genomics Data Science Community Network) is a consortium of educators who aim to create a world where researchers, educators, and students from diverse backgrounds are able to fully participate in genomic data science research. You can find more information about its mission and initiatives [here](https://www.gdscn.org/home).

## Motivation

One critical aspect of an undergraduate STEM education is hands-on research. Undergraduate research experiences enhance what students learn in the classroom as well as increase a student's interest in pursuing STEM careers ^1. It can also lead to improved scientific reasoning and increased academic performance overall ^2. However, many students at underresourced institutions like community colleges, Historically Black Colleges and Universities (HBCUs), tribal colleges and universities, and Hispanic-serving institutions have limited access to research opportunities compared to their cohorts at larger four-year colleges and R1 institutions. These students are also more likely to belong to groups that are already under-represented in STEM disciplines, particularly genomics and data science ^3 ^4.

The BioDIGS Project aims to be at the intersection of genomics, data science, cloud computing, and education.

## Target Audience

The activities in this guide are written for undergraduate students and beginning graduate students. Some sections require basic understanding of the R programming language, which is indicated at the beginning of the chapter.

## Platform

The activities in this guide are demonstrated on NHGRI's [AnVIL](https://anvilproject.org/) cloud computing platform. AnVIL is the preferred computing platform for the GDSCN. However, all of these activities can be done using your personal installation of R or using the online [Galaxy](usegalaxy.org) portal.

## Data

The data generated by the BioDIGS project is available through the [BioDIGS website](biodigs.org), as well as through an [AnVIL workspace](https://anvilproject.org). 
## Who did the soil sampling?

Soil sampling for this project was done by both faculty and student volunteers from schools that aren't traditional R1 research institutions. 

## Where is the funding from? 

Funding for this project is through Contract # 75N92022P00232 from the National Human Genome Research Institute awarded to Johns Hopkins University.

## References

1: Russell et al. 2007: https://doi.org/10.1126/science.1140384

2: Buffalari et al. 2020: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8040836/

3: Canner et al. 2017: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5398168/

4: GDSCN 2022: https://doi.org/10.1101/gr.276496.121