# Data

There are three major kinds of data available from BioDIGS: sample metadata, soil testing data, and genomics and metagenomics data. All of these are available for use in your classroom.

## Sample Metadata

This dataset contains information about the samples themselves, including GPS coordinates for the sample location, date the sample was taken, and the site name. This dataset is also available from the [BioDIGS website](https://biodigs.org/#site_data)

You can also see images of each sampling site and soil characteristics at the [sample map](https://biodigs.org/#sample_map).

## Soil Testing Data

This dataset includes basic information about the soil itself like pH, percentage of organic matter, variety of soil metal concentrations. The complete data dictionary is available [here](https://docs.google.com/spreadsheets/d/109xYUM48rjj33B76hZ3bNlrm8u-_S6uyoE_3wSCp0r0/edit#gid=188448677). The dataset is available at the [BioDIGS website](https://biodigs.org/#soil_data).

## Genomics and Metagenomics Data

You can access this data in both raw and processed forms.

More information coming soon!