# Research Team

This project is coordinated by the Genomics Data Science Community Network (GDSCN). You can read more about the GDSCN and its mission at the network's [website](https://www.gdscn.org/home).

Soil sampling for this project was done by both faculty and student volunteers from schools that aren't traditional R1 research institutions. Many of the faculty are also members of the GDSCN.

- **Annandale, VA**: Northern Virginia Community College
- **Atlanta, GA**: Spelman College
- **Baltimore, MD**: College of Southern Maryland, Notre Dame College of Maryland, Towson University
- **Bismark, ND**: United Tribes Technical College
- **El Paso, TX**: El Paso Community College, The University of Texas at El Paso
- **Fresno, CA**: Clovis Community College
- **Greensboro, NC**: North Carolina A&T State University
- **Harrisonburg, VA**: James Madison University
- **Honolulu, Hawai'i**: University of Hawai'i at Mānoa
- **Las Cruces, NM**: Doña Ana Community College
- **Montgomery County, MD**: Montgomery College, Towson University
- **Nashville, TN**: Meharry Medical College
- **New York, NY**: Guttman Community COllege CUNY
- **Petersburg, VA**: Virginia State University
- **Seattle, WA**: North Seattle College, Pierce College
- **Tsaile, AZ**: Diné College

## Funding

Funding for this project has been provided by the [National Human Genome Research Institute](https://www.genome.gov/) (Contract # 75N92022P00232 awarded to Johns Hopkins University), as well as by donations from [PacBio](https://www.pacb.com/) and [CosmosID](https://www.cosmosid.com/).

[Advances in Genome Biology and Technology](https://www.agbt.org/) provided funding support for several team members to attend AGBT 2024.

## Analytical and Computational Support

Computational support has been provided by NHGRI's [AnVIL](https://anvilproject.org/) cloud computing platform and [Galaxy](usegalaxy.org).


